package geoloc

var stateToCode = map[string]string{
	// "andaman and nicobar islands": "AN",
	// "dadra and nagar haveli":      "DN",
	// "daman and diu":               "DD",
	// "delhi":                       "DL",
	"andhra pradesh":    "AP",
	"uttar pradesh":     "UP",
	"arunachal pradesh": "AR",
	"himachal pradesh":  "HP",
	"jammu and kashmir": "JK",
	"west bengal":       "WB",
	"tamil nadu":        "TN",
	"madhya pradesh":    "MP",
	"assam":             "AS",
	"bihar":             "BR",
	"chandigarh":        "CH",
	"chhattisgarh":      "CT",
	"goa":               "GA",
	"gujarat":           "GJ",
	"haryana":           "HR",
	"jharkhand":         "JH",
	"karnataka":         "KA",
	"kerala":            "KL",
	"lakshadweep":       "LD",
	"maharashtra":       "MH",
	"manipur":           "MN",
	"meghalaya":         "ML",
	"mizoram":           "MZ",
	"nagaland":          "NL",
	"odisha":            "OR",
	"puducherry":        "PY",
	"punjab":            "PB",
	"rajasthan":         "RJ",
	"sikkim":            "SK",
	"telangana":         "TG",
	"tripura":           "TR",
	"uttarakhand":       "UT",
}
